export const ALL_DOCTOR_REQUEST = "ALL_DOCTOR_REQUEST";
export const ALL_DOCTOR_SUCCESS = "ALL_DOCTOR_SUCCESS";
export const ALL_DOCTOR_FAIL = "ALL_DOCTOR_FAIL";


// single doctor request 
export const DOCTOR_DETAILS_REQUEST = "DOCTOR_DETAILS_REQUEST";
export const DOCTOR_DETAILS_SUCCESS = "DOCTOR_DETAILS_SUCCESS";
export const DOCTOR_DETAILS_FAIL = "DOCTOR_DETAILS_FAIL";
// clear error 

//appointment 
export const USER_APPOINTMENT_REQUEST = "USER_APPOINTMENT_REQUEST";
export const USER_APPOINTMENT_SUCCESS = "USER_APPOINTMENT_SUCCESS";
export const USER_APPOINTMENT_FAIL = "USER_APPOINTMENT_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";
