export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

// REGISTER 
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"; 
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL"; 


// LOAD REGISTER USER 
export const LOAD_USER_REQUEST = "LOAD_REGISTER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_REGISTER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_REGISTER_FAIL";


// LOGIN AND LOGOUT 
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";


// CLEAR ERROR
export const CLEAR_ERRORS = "CLEAR_ERRORS";
